security:
  system:
    hashing:
      salt: hashing-salt

---
spring:
  config:
    activate:
      on-profile: dev, prd, tst
security:
  system:
    hashing:
      salt: ${SECURITY.SYSTEM.HASHING.SALT}