security:
  system:
    symmetric:
      salt: symmetric-salt
      secret-key: dHVzc2xlYy1hZXMtMjU2LWxvY2FsLXNlY3JldC1rZXk=

---
spring:
  config:
    activate:
      on-profile: dev, prd, tst
security:
  system:
    symmetric:
      salt: ${SECURITY.SYSTEM.SYMMETRIC.SALT}
      secret-key: ${SECURITY.SYSTEM.SYMMETRIC.SECRET-KEY}